# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': "Studio",
    'summary': "Create and customize your Odoo apps",
    'website': 'https://www.odoo.com/page/studio',
    'description': """
Studio - Customize Odoo
=======================

This addon allows the user to customize most element of the user interface, in a
simple and graphical way. It has two main features:

* create a new application (add module, top level menu item, and default action)
* customize an existing application (edit menus, actions, views, translations, ...)

Note: Only the admin user is allowed to make those customizations.
""",
    'category': 'Customizations/Studio',
    'sequence': 75,
    'version': '1.0',
    'depends': [
        'base_automation',
        'base_import_module',
        'mail',
        'web',
        'web_enterprise',
        'web_editor',
        'web_map',
        'web_gantt',
        'sms',
    ],
    'data': [
        'views/assets.xml',
        'views/actions.xml',
        'views/base_import_module_view.xml',
        'views/ir_actions_report_xml.xml',
        'views/ir_model_data.xml',
        'views/studio_approval_views.xml',
        'data/mail_templates.xml',
        'wizard/base_module_uninstall_view.xml',
        'security/ir.model.access.csv',
        'security/studio_security.xml',
    ],
    'application': True,
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'web_studio/static/src/js/background_image.js',
            'web_studio/static/src/js/approval_component.js',
            'web_studio/static/src/scss/approval_component.scss',
            'web_studio/static/src/js/views/renderers/form_renderer.js',
            'web_studio/static/src/js/views/renderers/list_renderer_eager.js',
            'web_studio/static/src/js/views/controllers/form_controller.js',
        ],
        'web_studio.assets': [
            'web_studio/static/src/js/action_manager.js',
            'web_studio/static/src/js/bus.js',
            'web_studio/static/src/js/systray_item.js',
            'web_studio/static/src/js/web_client.js',
            'web_studio/static/src/js/menu.js',
            'web_studio/static/src/js/common_menu_dialog.js',
            'web_studio/static/src/js/edit_menu.js',
            'web_studio/static/src/js/new_model.js',
            'web_studio/static/src/js/submenu.js',
            'web_studio/static/src/js/studio_home_menu.js',
            'web_studio/static/src/js/icon_creator.js',
            'web_studio/static/src/js/utils.js',
            'web_studio/static/src/js/tours/web_studio.js',
            'web_studio/static/src/js/model_configurator.js',
        ],
        'web_studio.studio_assets': [
            'web_studio/static/src/js/app_creator.js',
            'web_studio/static/src/js/py.js',
            'web_studio/static/src/js/common/**/*.js',
            'web_studio/static/src/js/reports/**/*.js',
            'web_studio/static/src/js/views/abstract_view.js',
            'web_studio/static/src/js/views/action_editor.js',
            'web_studio/static/src/js/views/action_editor_action.js',
            'web_studio/static/src/js/views/action_editor_sidebar.js',
            'web_studio/static/src/js/views/action_editor_view.js',
            'web_studio/static/src/js/views/new_view_dialog.js',
            'web_studio/static/src/js/views/view_components.js',
            'web_studio/static/src/js/views/view_editor_manager.js',
            'web_studio/static/src/js/views/view_editor_sidebar.js',
            'web_studio/static/src/js/views/map_view_dialog.js',
            'web_studio/static/src/js/views/renderers/search_renderer.js',
            'web_studio/static/src/js/views/renderers/list_renderer_lazy.js',
            'web_studio/static/src/js/views/view_editors/**/*.js',
            ('include', 'web._assets_helpers'),
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web_studio/static/src/scss/main.scss',
            'web_studio/static/src/scss/icons.scss',
            'web_studio/static/src/scss/mixins.scss',
            'web_studio/static/src/scss/action_editor.scss',
            'web_studio/static/src/scss/app_creator.scss',
            'web_studio/static/src/scss/model_configurator.scss',
            'web_studio/static/src/scss/form_editor.scss',
            'web_studio/static/src/scss/icon_creator.scss',
            'web_studio/static/src/scss/kanban_view.scss',
            'web_studio/static/src/scss/kanban_editor.scss',
            'web_studio/static/src/scss/list_editor.scss',
            'web_studio/static/src/scss/menu.scss',
            'web_studio/static/src/scss/new_field_dialog.scss',
            'web_studio/static/src/scss/new_view_dialog.scss',
            'web_studio/static/src/scss/report_editor.scss',
            'web_studio/static/src/scss/report_editor_manager.scss',
            'web_studio/static/src/scss/report_editor_sidebar.scss',
            'web_studio/static/src/scss/report_kanban_view.scss',
            'web_studio/static/src/scss/search_editor.scss',
            'web_studio/static/src/scss/sidebar.scss',
            'web_studio/static/src/scss/submenu.scss',
            'web_studio/static/src/scss/view_editor_manager.scss',
            'web_studio/static/src/scss/xml_editor.scss',
        ],
        'web.assets_tests': [
            'web_studio/static/tests/tours/**/*',
        ],
        'web_studio.report_assets': [
            ('include', 'web._assets_helpers'),
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web_studio/static/src/scss/report_iframe.scss',
        ],
        'web.qunit_suite_tests': [
            'web_studio/static/tests/webclient_test.js',
            'web_studio/static/tests/studio_home_menu_tests.js',
            'web_studio/static/tests/home_menu_wrapper_tests.js',
            'web_studio/static/tests/action_editor_action_tests.js',
            'web_studio/static/tests/app_creator_tests.js',
            'web_studio/static/tests/edit_menu_tests.js',
            'web_studio/static/tests/new_model_tests.js',
            'web_studio/static/tests/mock_server.js',
            'web_studio/static/tests/navigation_tests.js',
            'web_studio/static/tests/test_utils.js',
            'web_studio/static/tests/reports/**/*.js',
            'web_studio/static/tests/views/**/*.js',
        ],
        'web.assets_qweb': [
            'web_studio/static/src/xml/*.xml',
        ],
    }
}
