# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': "Documents Spreadsheet",
    'version': '1.0',
    'category': 'Productivity/Documents',
    'summary': 'Documents Spreadsheet',
    'description': 'Documents Spreadsheet',
    'depends': ['documents'],
    'data': [
        'data/documents_data.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/documents_views.xml',
        'wizard/save_spreadsheet_template.xml',
    ],
    'application': False,
    'installable': True,
    'auto_install': True,
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'documents_spreadsheet/static/src/js/o-spreadsheet/o_spreadsheet.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/o_spreadsheet_loader.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/o_spreadsheet_extended.js',
            'documents_spreadsheet/static/src/js/spreadsheet_abstract_action.js',
            'documents_spreadsheet/static/src/js/spreadsheet_action.js',
            'documents_spreadsheet/static/src/js/spreadsheet_template_action.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_component.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_control_panel.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_name.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_template_dialog.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_pivot_dialog.js',
            'documents_spreadsheet/static/src/js/components/spreadsheet_pivot_dialog_table.js',
            'documents_spreadsheet/static/src/js/documents_inspector.js',
            'documents_spreadsheet/static/src/js/documents_kanban_record.js',
            'documents_spreadsheet/static/src/js/spreadsheet_kanban_view.js',
            'documents_spreadsheet/static/src/js/documents_kanban_controller.js',
            'documents_spreadsheet/static/src/js/documents_spreadsheet_controller_mixin.js',
            'documents_spreadsheet/static/src/js/documents_list_controller.js',
            'documents_spreadsheet/static/src/js/spreadsheet_list_view.js',
            'documents_spreadsheet/static/src/js/spreadsheet_template_list_view.js',
            'documents_spreadsheet/static/src/js/pivot_controller.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/widgets/field_selector_widget.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/widgets/model_selector_widget.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/widgets/tag_selector_widget.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/context_menu/pivot_context_menu.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/context_menu/menu_item_registry.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/context_menu/pivot_side_panel.js',
            'documents_spreadsheet/static/src/js/components/filter_editor_side_panel.js',
            'documents_spreadsheet/static/src/js/components/global_filters_side_panel.js',
            'documents_spreadsheet/static/src/js/components/filter_date_value.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/filter_component.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/autofill.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/pivot_utils.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/pivot_actions.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/pivot_cache.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/core/pivot_plugin.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/ui/pivot_structure_plugin.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/ui/pivot_template_plugin.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/helpers.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/filters_plugin.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/plugins/cancelled_reason.js',
            'documents_spreadsheet/static/src/js/o-spreadsheet/functions/pivot_functions.js',
            'documents_spreadsheet/static/src/js/spreadsheet_selector_dialog.js',
            'documents_spreadsheet/static/src/scss/spreadsheet.scss',
        ],
        'web.qunit_suite_tests': [
            'documents_spreadsheet/static/tests/test_utils.js',
            'documents_spreadsheet/static/tests/pivot_controller_test.js',
            'documents_spreadsheet/static/tests/spreadsheet_test.js',
            'documents_spreadsheet/static/tests/pivot_template_test.js',
        ],
        'web.assets_tests': [
            'documents_spreadsheet/static/tests/tours/**/*',
        ],
        'web.assets_qweb': [
            'documents_spreadsheet/static/src/xml/*.xml',
        ],
    }
}
